# Site settings
name: Rameshkumar Tech blog
title: Rameshkumar	Tech blog
email: trkrameshkumar@gmail.com
description: "This is my first blog , and i build this blog on  jekyll , it is really awesome"
baseurl: "/"
url: "http://trkrameshkumar.github.io"

# Build settings
markdown: kramdown
permalinks: pretty
