title:        Ramesh Kumar
tagline:      'Ramesh kumar tech blog'
description: "Software developer, at vakilserach.com"
url:          http://trkrameshkumar.github.io
username: "trkrameshkumar"
markdown:     rdiscount
permalink:    pretty
highlighter: pygments
paginate:     5

