title:        Ramesh Kumar
tagline:      'Ramesh kumar tech blog'
description: "Senior Ruby on Rails Developer"
url:          http://trkrameshkumar.github.io
username: "trkrameshkumar"
markdown:     rdiscount
permalink:    pretty
highlighter: pygments
exclude: [vendor]
paginate:     5

