title:        Ramesh Kumar
tagline:      'Ramesh kumar tech blog'
description: "Web developer, at vakilserach.com"
url:          http://trkrameshkumar.github.io
username: "trkrameshkumar"
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
